tagline: 'PumpUp <b>dev</b>'

exclude:
  - '*.sublime-project'
  - '*.sublime-workspace'
  - '*.log'
  - '*.sh'
  - package.json
  - README.md
  - node_modules
  - scripts

markdown: redcarpet
redcarpet:
  extensions:
    - autolink
    - hard_wrap
    - highlight
    - strikethrough
    - smart
    - space_after_headers
    - superscript
    - tables
    - with_toc_data

permalink: /post/:title

url: http://pumpup.com/
url_github: https://github.com/pumpupapp/

emoji_dir: https://github.global.ssl.fastly.net/images/icons/emoji/

paginate: 5
paginate_path: 'page/:num'

gems:
  - jekyll-paginate
